# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
matrix:
  include:
  - os: linux
    r: release
    addons:
        apt:
            packages:
                - libicu-dev
  - os: linux
    r: oldrel
  - os: linux
    r: devel
  - os: osx
    r: release
  - os: osx
    r: devel

warnings_are_errors: true
r_build_args: "--no-manual"
r_check_args: "--no-manual --as-cran"
